### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by ericphanson** [HFriberg/cblib-base#1]
I tried to run the `qssp30.cbf` example from the README but couldn't get it to work. I'd appreciate any help.

Here is what I did: I cloned this repo, downloaded `qssp30.cbf` and put it in the `instances/cbf` directory, and ran
```
python scripts/run.py runmosek -f ./instances/cbf/qssp30.cbf
```
This runs the optimization with Mosek ok, but then errors when it comes to the `getsolution` part.
Here's the full output
```
File read: 0.16 seconds
Solver read: 0.05 seconds
Problem
  Name                   :
  Objective sense        : min
  Type                   : CONIC (conic optimization problem)
  Constraints            : 11255
  Cones                  : 1891
  Scalar variables       : 18820
  Matrix variables       : 0
  Integer variables      : 0

Optimizer started.
Presolve started.
Linear dependency checker started.
Linear dependency checker terminated.
Eliminator - tries                  : 0                 time                   : 0.00
Lin. dep.  - tries                  : 1                 time                   : 0.01
Lin. dep.  - number                 : 0
Presolve terminated. Time: 0.02
GP based matrix reordering started.
GP based matrix reordering terminated.
Problem
  Name                   :
  Objective sense        : min
  Type                   : CONIC (conic optimization problem)
  Constraints            : 11255
  Cones                  : 1891
  Scalar variables       : 18820
  Matrix variables       : 0
  Integer variables      : 0

Optimizer  - threads                : 4
Optimizer  - solved problem         : the primal
Optimizer  - Constraints            : 1799
Optimizer  - Cones                  : 1888
Optimizer  - Scalar variables       : 7378              conic                  : 7375
Optimizer  - Semi-definite variables: 0                 scalarized             : 0
Factor     - setup time             : 0.05              dense det. time        : 0.00
Factor     - ML order time          : 0.00              GP order time          : 0.03
Factor     - nonzeros before factor : 2.21e+04          after factor           : 1.08e+05
Factor     - dense dim.             : 0                 flops                  : 8.39e+06
Factor     - GP saved nzs           : 3857              GP saved flops         : 5.86e+04
ITE PFEAS    DFEAS    GFEAS    PRSTATUS   POBJ              DOBJ              MU       TIME
0   8.8e-01  1.2e+00  1.0e+00  0.00e+00   0.000000000e+00   0.000000000e+00   1.0e+00  0.10
1   1.1e-01  1.4e-01  1.5e-01  3.00e+00   -1.618209852e-01  2.224148680e+00   1.2e-01  0.11
2   1.2e-02  1.6e-02  5.5e-02  1.13e+00   -1.509381771e+00  -1.274262985e+00  1.4e-02  0.12
3   6.8e-03  9.0e-03  4.4e-02  1.01e+00   -3.604951787e+00  -3.493092526e+00  7.8e-03  0.13
4   3.1e-03  4.1e-03  3.3e-02  1.01e+00   -5.001278222e+00  -4.960695049e+00  3.6e-03  0.14
5   1.3e-03  1.7e-03  2.5e-02  1.00e+00   -5.771652139e+00  -5.760504960e+00  1.5e-03  0.14
6   4.3e-04  5.6e-04  1.8e-02  1.00e+00   -6.191455355e+00  -6.189457873e+00  4.9e-04  0.15
7   9.8e-05  1.3e-04  1.3e-02  1.00e+00   -6.408013135e+00  -6.407944617e+00  1.1e-04  0.16
8   1.6e-05  2.1e-05  7.6e-03  1.00e+00   -6.480662561e+00  -6.480675867e+00  1.8e-05  0.17
9   1.5e-06  1.9e-06  2.6e-03  1.00e+00   -6.495139808e+00  -6.495141474e+00  1.7e-06  0.18
10  8.1e-08  1.1e-07  6.1e-04  1.00e+00   -6.496589078e+00  -6.496589172e+00  9.3e-08  0.19
11  6.0e-09  7.9e-09  1.7e-04  1.00e+00   -6.496669352e+00  -6.496669359e+00  6.9e-09  0.20
Optimizer terminated. Time: 0.21


Interior-point solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : OPTIMAL
  Primal.  obj: -6.4966693517e+00   nrm: 6e+00    Viol.  con: 2e-13    var: 0e+00    cones: 6e-10
  Dual.    obj: -6.4966693586e+00   nrm: 5e+00    Viol.  con: 0e+00    var: 8e-09    cones: 3e-09
'module' object has no attribute 'array'
Traceback (most recent call last):
  File "scripts/run.py", line 159, in <module>
    run(solver, probfile, solfile, paramfile, printer, callback)
  File "scripts/run.py", line 56, in run
    ppsol = solver.getsolution()
  File "/Users/eh540/cblib-base/cblib/scripts/solvers/runmosek.py", line 59, in getsolution
    xx  = mosek.array.zeros(varnum, float)
AttributeError: 'module' object has no attribute 'array'
```

I'm on Python 2.7.10 (trying with Python 3 gave errors that seemed related to not using Python 2), and pip list shows
```bash
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package    Version
---------- -------
Mosek      8.1.80
numpy      1.16.3
pip        19.1
scipy      1.2.1
setuptools 41.0.1
wheel      0.33.1
```

**Comment by HFriberg** [comment]
Ever since I finished my phd-thesis and we simplified the presentation of instances on http://cblib.zib.de/ to a plain directory listing + readme file, I have not had any needs for this benchmark toolkit myself and therefore discontinue maintenance from this day on.

Should anyone be interested in fixing this bug I offer collaborator access rights to push changes and much more on cblib-base. This particular issue is a good place to start as you just have to replace `mosek.array.zeros` by `numpy.zeros` in `runmosek.py` to account for the interface changes made from MOSEK 7 to MOSEK 8.

**Comment by ericphanson** [comment]
That makes sense. I don't think I, for example, would be a good maintainer since most of my work doesn't relate to convex optimization (and I don't know much python), but I made a pull request with the changes you mentioned. Thanks for making this nice library of problems.
